# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: cleadb
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: cleadb
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    user: username
    database: cleadb
    jsonData:
      sslmode: disable
    secureJsonData:
      password: password
