version: "3.5"
services:
  crypto-server:
    build: robert-crypto-grpc-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/robert
      - ROBERT_CRYPTO_SERVER_KEYSTORE_TYPE=PKCS12
      - ROBERT_CRYPTO_SERVER_KEYSTORE_FILE=file:/keystore.p12
      - ROBERT_CRYPTO_SERVER_KEYSTORE_PASSWORD=1234
      - FAKETIME_TIMESTAMP_FILE=/etc/faketime.d/faketime
    depends_on:
      - postgres
    volumes:
      - faketime:/etc/faketime.d/

  ws-rest:
    build: robert-server-ws-rest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/protectedRobertDB
      - ROBERT_CRYPTO_SERVER_HOST=crypto-server
      - SUBMISSION_CODE_SERVER_URL=http://mock-submission-code-server:1080
      - CAPTCHA_INTERNAL_HOSTNAME=http://mock-captcha:1080
      - CAPTCHA_INTERNAL_VERIFY_URL=http://mock-captcha:1080/private/api/v1/captcha/{captchaId}/checkAnswer
      - PUSH_SERVER_HOST=mock-push-notif-server
      - PUSH_SERVER_PORT=1080
      - ESR_LIMIT=0
      - FAKETIME_TIMESTAMP_FILE=/etc/faketime.d/faketime
    ports:
      - "8086:8086"
    depends_on:
      - mongo
      - crypto-server
      - mock-submission-code-server
      - mock-captcha
    volumes:
      - faketime:/etc/faketime.d/

  batch:
    build: robert-server-batch
    environment:
      - ROBERT_CRYPTO_SERVER_HOST=crypto-server
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/protectedRobertDB
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_ENABLED=true
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_BASEURL=http://pushgateway:9091
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_GROUPINGKEY_INSTANCE=robert-batch
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_SHUTDOWNOPERATION=DELETE
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_PUSHRATE=5s
      - FAKETIME_TIMESTAMP_FILE=/etc/faketime.d/faketime
    depends_on:
      - mongo
      - crypto-server
    volumes:
      - faketime:/etc/faketime.d/

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=robert
      - POSTGRES_DB=robert
      - POSTGRES_USER=robert

  flyway:
    image: flyway/flyway:7.8
    command: migrate -connectRetries=60
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/robert
      FLYWAY_USER: robert
      FLYWAY_PASSWORD: robert
    volumes:
      - ./robert-crypto-grpc-server-storage/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  mongo:
    image: "mongo:4.2.11"
    ports:
      - "27017:27017"

  mock-captcha:
    image: mockserver/mockserver:mockserver-5.13.2
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /expectations.json
    volumes:
      - ./docker-compose/mock-server/captcha.json:/expectations.json:ro

  mock-push-notif-server:
    image: mockserver/mockserver:mockserver-5.13.2
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /expectations.json
    volumes:
      - ./docker-compose/mock-server/push-notif-server.json:/expectations.json:ro

  mock-submission-code-server:
    image: mockserver/mockserver:mockserver-5.13.2
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /expectations.json
    volumes:
      - ./docker-compose/mock-server/submission-code-server.json:/expectations.json:ro

  prometheus:
    profiles:
      - monitoring
    image: prom/prometheus:v2.32.1
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - "9090:9090"
    volumes:
      - ./docker-compose/prometheus/config.yml:/etc/prometheus/config.yml:ro

  pushgateway:
    profiles:
      - monitoring
    image: prom/pushgateway:v1.4.2

  grafana:
    profiles:
      - monitoring
    image: grafana/grafana:6.7.2
    volumes:
      - ./docker-compose/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "3000:3000"

volumes:
  faketime:
