version: '3.5'
services:
  postgresql-robert:
    image: 'postgres:9.6'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=robert
      - POSTGRES_DB=robert
      - POSTGRES_USER=robert
  robert-crypto-server:
    build:
      context: ./robert-crypto-grpc-server
      dockerfile: ./src/main/docker/Dockerfile
    container_name: robert-crypto-grpc-server
    ports:
      - "9090:9090"
      - "19090:19090"
    environment:
      - ROBERT_CRYPTO_SERVER_CONFIG_FILE=/conf/softhsm2.cfg
      - ROBERT_CRYPTO_SERVER_DB_URL=jdbc:postgresql://postgresql-robert:5432/robert
      - JAVA_OPTS=-Xrunjdwp:transport=dt_socket,address=*:19090,server=y,suspend=n
    depends_on:
      - postgresql-robert
  mongo:
    image: 'mongo:4.2.5'
    ports:
      - "27017:27017"
  robert-server-ws-rest:
    build:
      context: ./robert-server-ws-rest
      dockerfile: ./src/main/docker/Dockerfile
    container_name: robert-server-ws-rest
    environment:
      - ROBERT_JWT_PRIVATE_KEY=${ROBERT_JWT_PRIVATE_KEY}
      - ROBERT_JWT_TOKEN_DECLARE_PUBLIC_KID=${ROBERT_JWT_TOKEN_DECLARE_PUBLIC_KID}
      - ROBERT_JWT_TOKEN_DECLARE_PRIVATE_KEY=${ROBERT_JWT_TOKEN_DECLARE_PRIVATE_KEY}
      - ROBERT_JWT_TOKEN_ANALYTICS_PRIVATE_KEY=${ROBERT_JWT_TOKEN_ANALYTICS_PRIVATE_KEY}
    ports:
      - "8086:8086"
    volumes:
      - ./environment-setup/dev/compose/robert-server-ws-rest-config:/work/config
      - ./environment-setup/dev/compose/logs:/logs
    deploy:
      restart_policy:
        condition: on-failure
  mock-captcha:
    image: mockserver/mockserver:mockserver-5.11.2
    command: -logLevel DEBUG -serverPort 8055
    ports:
      - "8055:8055"
    volumes:
      - ./environment-setup/dev/compose/captcha-orange-server-config:/mock-expectation
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/mock-expectation/mock-server-expectation.json
    container_name: mock-captcha
  mock-submission-code-server:
    image: mockserver/mockserver:mockserver-5.11.2
    command: -logLevel DEBUG -serverPort 8087
    ports:
      - "8087:8087"
    volumes:
      - ./environment-setup/dev/compose/submission-code-server-ws-rest-config:/mock-expectation
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/mock-expectation/mock-server-expectation.json
    container_name: mock-submission-code-server
networks:
  default:
    external:
      name: ${TAC_DOCKER_COMPOSE_NETWORK}