version: "3.5"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=robert
      - POSTGRES_DB=robert
      - POSTGRES_USER=robert

  flyway:
    image: flyway/flyway:7.8
    command: migrate -connectRetries=60
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/robert
      FLYWAY_USER: robert
      FLYWAY_PASSWORD: robert
    volumes:
      - ./robert-crypto-grpc-server-storage/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  crypto-server:
    build: robert-crypto-grpc-server
    ports:
      - "9090:9090"
      - "19090:19090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/robert
      - ROBERT_CRYPTO_SERVER_KEYSTORE_CONFIG_FILE=/conf/softhsm2.cfg
      - ROBERT_CRYPTO_SERVER_KEYSTORE_TYPE=PKCS12
      - ROBERT_CRYPTO_SERVER_KEYSTORE_FILE=file:/work/config/keystore.p12
    depends_on:
      - postgres

  mongo:
    image: "mongo:4.2.5"
    ports:
      - "27017:27017"

  mock-captcha:
    image: mockserver/mockserver:mockserver-5.11.2
    command: -logLevel DEBUG -serverPort 8055
    ports:
      - "8055:8055"
    volumes:
      - ./docker-compose/mock-captcha-orange-server-config:/mock-expectation
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/mock-expectation/mock-server-expectation.json

  mock-submission-code-server:
    image: mockserver/mockserver:mockserver-5.11.2
    command: -logLevel DEBUG -serverPort 8087
    ports:
      - "8087:8087"
    volumes:
      - ./docker-compose/mock-submission-code-server-ws-rest-config:/mock-expectation
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/mock-expectation/mock-server-expectation.json

  ws-rest:
    build: robert-server-ws-rest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/protectedRobertDB
      - ROBERT_CRYPTO_SERVER_HOST=crypto-server
      - SUBMISSION_CODE_SERVER_HOST=mock-submission-code-server
      - CAPTCHA_INTERNAL_HOSTNAME=http://mock-captcha:8055
      - CAPTCHA_INTERNAL_VERIFY_URL=http://mock-captcha:8055/private/api/v1/captcha/{captchaId}/checkAnswer
      - PUSH_SERVER_HOST=robert-push-notif-server-ws-rest
      - ESR_LIMIT=0
    ports:
      - "8086:8086"
    depends_on:
      - mongo
      - crypto-server
      - mock-submission-code-server
      - mock-captcha

  batch:
    build: robert-server-batch
    environment:
      - ROBERT_CRYPTO_SERVER_HOST=crypto-server
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/protectedRobertDB
    depends_on:
      - mongo
      - crypto-server
      - mock-submission-code-server
      - mock-captcha
