controller:
  path:
    prefix: /api/clea
server:
  port: 8088

# Available endpoints for the monitoring
management:
  endpoints:
    web:
      exposure:
        include: ${CLEA_SERVER_MONITORING_ENDPOINTS:health,metrics}

clea:
  conf:
    duplicateScanThresholdInSeconds: 10800
    retentionDurationInDays: 14
    security:
      report:
        checkAuthorization: false
        robertJwtPublicKey: TODO

logging:
  level:
    fr.gouv.clea.ws: INFO

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: group1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: fr.gouv.clea.ws.utils.KafkaLSPSerializer
    template:
      default-topic: cleaQrCodes

