# contains only static configurations that are not added to consul

logging:
  level:
    fr.gouv.clea.consumer: INFO

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: fr.gouv.clea.ws.utils.KafkaSerializer
