controller:
  path:
    prefix: /api/clea
server:
  port: 8088

# Available endpoints for the monitoring
management:
  endpoints:
    web:
      exposure:
        include: ${CLEA_SERVER_MONITORING_ENDPOINTS:health,metrics}

clea:
  conf:
    duplicateScanThreshold: 10800
    retentionDuration: 14
    security:
      crypto:
        manualCTAuthoritySecretKey: 3108f08b1485adb6f72cfba1b55c7484c906a2a3a0a027c78dcd991ca64c97bd
      report:
        checkAuthorization: false
        robertJwtPublicKey: TODO

logging:
  level:
    fr.gouv.clea.ws: DEBUG

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: group1
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: fr.gouv.clea.ws.utils.KafkaLSPSerializer
    template:
      default-topic: qrCodes

