clea:
  conf:
    duplicateScanThresholdInSeconds: 10800
    retentionDurationInDays: 14
    security:
      report:
        checkAuthorization: false
        robertJwtPublicKey: TODO

controller:
  path:
    prefix: /api/clea

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: cleaQrCodes
