# This docker compose file allow to deploy all  mandatory components that are not easy to launch from your IDE of your
# development laptop.

version: '3.5'
services:
  mongoanalytics:
    image: 'mongo:4.2.5'
    ports:
      - "27018:27017"
  esanalytics:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: esanalytics
    environment:
      - node.name=esanalytics
      - discovery.type=single-node
      - cluster.name=elasticsearchanalytics
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esanalytics:/usr/share/elasticsearch/data/analytics
    ports:
      - 9200:9200
    networks:
      - network_analytics
  kibanalytics:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibanalytics
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://esanalytics:9200
      ELASTICSEARCH_HOSTS: '["http://esanalytics:9200"]'
    networks:
      - network_analytics
    depends_on:
      - esanalytics
  logstashanalytics:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - network_analytics
    depends_on:
      - esanalytics
      - kafkaanalytics
  zookeeperanalytics:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - network_analytics
  kafkaanalytics:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "19092:19092"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaanalytics:9092,OUTSIDE://_{HOSTNAME_COMMAND}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeperanalytics:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network_analytics
  kafdropanalytics:
    image: obsidiandynamics/kafdrop:3.27.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafkaanalytics:19092"
      JVM_OPTS: "-Xms128M -Xmx512M -Xss512K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - network_analytics
    depends_on:
      - kafkaanalytics

volumes:
  esanalytics:
    driver: local

networks:
  network_analytics:
    driver: bridge
