global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "springboot-exporter application"
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names: ["ws-rest", "crypto-server"]
        type: A
        port: 8081
    relabel_configs:
      - source_labels: ["__meta_dns_name", "__address__"]
        separator: "-"
        target_label: instance
        replacement: "${1}"
