robert:
  ws-rest-base-url: http://gateway:8000
  crypto-public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7fAxfrLtG5tXyjomCOg9r1wNnr9len4m9sTflJUHDdkwubKyidTtFkVfNLrM91yuffdrpJZe9XOkof8P+zPGDg=="
  batch-command: "docker-compose up --no-recreate batch"

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/protectedRobertDB
  datasource:
    url: jdbc:postgresql://postgres:5432/robert
    username: robert
    password: robert

logging.level:
  root: warn
  fr.gouv: info
