robert:
  ws-rest-base-url: http://localhost:8086
  crypto-public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7fAxfrLtG5tXyjomCOg9r1wNnr9len4m9sTflJUHDdkwubKyidTtFkVfNLrM91yuffdrpJZe9XOkof8P+zPGDg=="
  batch-command: "docker-compose up batch"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/protectedRobertDB
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/robert
    username: robert
    password: robert

logging.level:
  root: warn
  fr.gouv: info
