robert:
  ws-rest-base-url: http://gateway:8000/api/v6
  ws-rest-internal-base-url: http://gateway:8000/internal/api/v2
  crypto-public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7fAxfrLtG5tXyjomCOg9r1wNnr9len4m9sTflJUHDdkwubKyidTtFkVfNLrM91yuffdrpJZe9XOkof8P+zPGDg==
  crypto-datasource:
    url: jdbc:postgresql://postgres:5432/robert
    username: robert
    password: robert
  captcha-datasource:
    url: jdbc:postgresql://postgres:5432/robert
    username: robert
    password: robert
  submission-jwt-signing-key: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBTNNLOcRp7Bksc//nB+6DlOCyCtDlvGHiz9UWVcGZoag==
  batch-command: "docker-compose up --no-recreate batch"

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/protectedRobertDB

logging.level:
  root: warn
  fr.gouv: info
  fr.gouv.stopc.e2e.mobileapplication.repository: debug
