spring:
  datasource:
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect # even with h2 database
    # Manage it's batch metadata tables
    initialize-schema: never
    #prevent job to launch on startup
    job:
      enabled: true
  flyway:
    enabled: "false"
    baseline-on-migrate: "true"
    locations: classpath:db/migration/{vendor}
  jackson:
    serialization:
      indent-output: true

clea:
  conf:
    exposure:
      enabled: "false"
    risk:
      enabled: "true"
      rules: # FIXME: change with real values
        # venueType, venueCat1, venueCat2, clusterThresholdBackward, clusterThresholdForward, riskLevelBackward, riskLevelForward
        - '*,*,*,3,1,3.0,2.0'
  batch:
    cluster:
      duration-unit-in-seconds: 1800
      static-prefix-length: ${CLEA_BATCH_PREFIX_LENGTH:2}
      files-output-path: ${CLEA_BATCH_OUTPUT_PATH:/tmp/v1}
      grid-size: 6
      identification-step-chunk-size: 1000
      indexation-step-chunk-size: 1000
      prefixes-computing-step-chunk-size: 1000