spring:
  datasource:
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect # even with h2 database

  batch:
    # Manage it's batch metadata tables
    initialize-schema: never
    #prevent job to launch on startup
    job:
      enabled: true
  flyway:
    enabled: "false"
    baseline-on-migrate: "true"
    locations: classpath:db/migration/{vendor}

clea:
  batch:
    cluster:
      duration-unit-in-seconds: 3600
      static-prefix-length: ${CLEA_BATCH_PREFIX_LENGTH:2}
      files-output-path: ${CLEA_BATCH_OUTPUT_PATH:/tmp/v1}
      #TODO: totally arbitrary values, find out actual plausible values
      grid-size: 6
      identification-step-chunk-size: 1000
      indexation-step-chunk-size: 1000