spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/cleadb
    username: username
    password: password

  batch:
    # Manage it's batch metadata tables
    initialize-schema: always
    cluster:
      output-path: /tmp/v1