spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${CLEA_DATABASE_URL:jdbc:postgresql://localhost:5432/clea?ssl=false}
    username: ${CLEA_DATABASE_USERNAME:clea}
    password: ${CLEA_DATABASE_PASSWORD:aelc}
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect // even with h2 database

  batch:
    # Manage it's batch metadata tables 
    initialize-schema: always
    #prevent job to launch on startup
    job:
      enabled: true
  flyway:
    enabled: "true"
    baseline-on-migrate: "true"
    locations: classpath:db/migration/{vendor}

clea:
  batch:
    duration-unit-in-seconds: 1800
    cluster:
      static-prefix-length: ${CLEA_BATCH_PREFIX_LENGTH:2}
      files-output-path: ${CLEA_BATCH_OUTPUT_PATH:/tmp/v1}
      #TODO: totally arbitrary values, find out actual plausible values
      grid-size: ${CLEA_BATCH_CLUSTER_GRID_SIZE:4}
      chunk-size: ${CLEA_BATCH_CLUSTER_CHUNK_SIZE:1000}

