spring:
  datasource:
    driverClassName: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect # even with h2 database

  batch:
    # Manage it's batch metadata tables 
    initialize-schema: never
    #prevent job to launch on startup
    job:
      enabled: true
  flyway:
    enabled: "false"
    baseline-on-migrate: "true"
    locations: classpath:db/migration/{vendor}

clea:
  conf:
    exposure:
      enabled: "false"
    risk:
      enabled: "true"
      rules:
        # venueType, venueCat1, venueCat2, clusterThresholdBackward, clusterThresholdForward, riskLevelBackward, riskLevelForward
        - '1,1,1,3,1,3.0,2.0'
        - '*,*,*,3,1,3.0,2.0'
        - '3,*,*,3,1,3.0,2.0'
        - '*,*,*,1,1,3.0,2.0'
  batch:
    duration-unit-in-seconds: 3600
    cluster:
      static-prefix-length: ${CLEA_BATCH_PREFIX_LENGTH:2}
      files-output-path: ${CLEA_BATCH_OUTPUT_PATH:/tmp/v1}
      #TODO: totally arbitrary values, find out actual plausible values
      grid-size: ${CLEA_BATCH_CLUSTER_GRID_SIZE:4}
      chunk-size: ${CLEA_BATCH_CLUSTER_CHUNK_SIZE:1000}
