spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cleadb
    username: username
    password: password

  batch:
    # Manage it's batch metadata tables 
    initialize-schema: always
