apiVersion: batch/v1
kind: CronJob
metadata:
  name: robert-batch-job
  namespace: robert-batch
  labels:
    app: robert-batch
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: robert-batch
        spec:
          containers:
            - name: robert-batch-app
              image: batch-image
              imagePullPolicy: Always
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: ROBERT_CRYPTO_SERVER_HOST
                  value: "robert-crypto-service.robert-crypto.svc.cluster.local"
                - name: ROBERT_CRYPTO_SERVER_PORT
                  value: "9090"
                - name: SPRING_DATA_MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: batch-secrets
                      key: SPRING_DATA_MONGODB_URI
                - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
                  value: "true"
                - name: SPRING_FLYWAY_BASELINE_VERSION
                  value: "0"
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "1"
                  memory: 2Gi
          restartPolicy: Never
          imagePullSecrets:
            - name: poc-inttac-poc-img-push-pull-secret
          nodeSelector:
            caascad.io/nodepool: "pod-tac"
