apiVersion: batch/v1
kind: CronJob
metadata:
  name: robert-batch-job
  namespace: robert-batch
  labels:
    app: robert-batch
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: robert-batch
        spec:
          containers:
            - name: robert-batch-app
              image: batch-image
              imagePullPolicy: Always
              env:
                - name: ROBERT_PROTOCOL_SCORING_ALGO_RSSI
                  value: "-40"
                - name: ROBERT_PROTOCOL_RISK_THRESHOLD
                  value: "0.1"
                - name: ROBERT_PROTOCOL_HELLO_TOLERANCE
                  value: "480"
                - name: ROBERT_SCORING_DELTAS
                  value: "39.0,27.0,23.0,21.0,20.0,15.0"
                - name: ROBERT_SCORING_RSSI_MAX
                  value: "-35"
                - name: ROBERT_PROTOCOL_CONTAGIOUS_PERIOD
                  value: "14"
                - name: ROBERT_SCORING_SCORING_ALGO_R0
                  value: "0.0071"
                - name: ROBERT_PROTOCOL_RISK_FLAG_RETENTION_PERIOD
                  value: "7"
                - name: ROBERT_CRYPTO_SERVER_HOST
                  value: "robert-crypto-service.robert-crypto.svc.cluster.local"
                - name: ROBERT_CRYPTO_SERVER_PORT
                  value: "9090"
                - name: SPRING_DATA_MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: batch-secrets
                      key: SPRING_DATA_MONGODB_URI
                - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
                  value: "true"
                - name: SPRING_FLYWAY_BASELINE_VERSION
                  value: "0"
          restartPolicy: Never
          imagePullSecrets:
            - name: poc-inttac-poc-img-push-pull-secret
          nodeSelector:
            caascad.io/nodepool: "pod-tac"
