apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-job-creator
  namespace: robert-batch
rules:
  - apiGroups:
      - batch
      - extensions
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - create
      - get
      - list
