version: "3.8"
services:
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    deploy:
      restart_policy:
        condition: on-failure      
  robert-server-ws-rest:
    image: registry.gitlab.inria.fr/stemcovid19/tac-server/backend-server/robert-server-ws-rest:${ROBERT_SERVER_TAG}
    container_name: robert-server-ws-rest
    environment:
      - ROBERT_JWT_PRIVATE_KEY=${ROBERT_JWT_PRIVATE_KEY}
      - ROBERT_JWT_TOKEN_DECLARE_PUBLIC_KID=${ROBERT_JWT_TOKEN_DECLARE_PUBLIC_KID}
      - ROBERT_JWT_TOKEN_DECLARE_PRIVATE_KEY=${ROBERT_JWT_TOKEN_DECLARE_PRIVATE_KEY}
    ports:
      - "8086:8086"
    volumes:
      - ${PWD}/robert-server-ws-rest-config:/work/config
      - ${PWD}/logs:/logs
      - ${PWD}/resources/CC.png:/tmp/CC.png
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: ["java","-jar", "/app.jar", "--spring.config.location=file:/work/config/application.properties"]
networks:
  default:
    external:
      name: ${TAC_DOCKER_COMPOSE_NETWORK}