version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=robert 
      - POSTGRES_DB=robert
      - POSTGRES_USER=robert
    deploy:
      restart_policy:
        condition: on-failure
  robert-crypto-grpc-server:
    image: registry.gitlab.inria.fr/stopcovid19/backend-server/robert-crypto-grpc-server:${ROBERT_CRYPTO_TAG}
    container_name: robert-crypto-grpc-server
    ports:
      - "9090:9090"
      #TODO: remove debug port declaration before merging
      - "19090:19090"
    environment:
      - JAVA_OPTS=-Xrunjdwp:transport=dt_socket,address=19090,server=y,suspend=n
#      TODO: replace with following line for java 11
#      - JAVA_OPTS=-Xrunjdwp:transport=dt_socket,address=:19090,server=y,suspend=n
    volumes:
      - ${PWD}/robert-crypto-grpc-server-config:/work/config
      - ${PWD}/logs:/logs
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: ["/entrypoint.sh"]
networks:
  default:
    external:
      name: ${TAC_DOCKER_COMPOSE_NETWORK}