version: "3.8"
services:
  captcha-orange-server:
    image: mockserver/mockserver:mockserver-5.11.2
    container_name: captcha-orange-server
    command: -logLevel DEBUG -serverPort 8055
    ports:
      - "8055:8055"
    volumes:
      - ./captcha-orange-server-config:/mock-expectation
    deploy:
      restart_policy:
        condition: on-failure
networks:
  default:
    external:
      name: ${TAC_DOCKER_COMPOSE_NETWORK}
    