# contains only static configurations that are not added to consul

logging:
  level:
    fr.gouv.clea.consumer: INFO

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    open-in-view: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: fr.gouv.clea.consumer.utils.KafkaDeserializer
  main:
    web-application-type: none
  output:
    ansi:
      enabled: ALWAYS
