clea:
  conf:
    retentionDuration: 14
    scheduling:
      purge:
        cron: "0 0 1 * * *"
        enabled: false
logging:
  level:
    fr.gouv.tacw: DEBUG
spring:
  jpa:
    generate-ddl: true
    open-in-view: false
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: group1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: fr.gouv.tacw.utils.KafkaLSPDeserializer
    template:
      default-topic: qrCodes
  main:
    web-application-type: none
  output:
    ansi:
      enabled: ALWAYS
