clea:
  conf:
    cleaClockDriftInSecs: 300
    driftBetweenDeviceAndOfficialTimeInSecs: 300
    retentionDurationInDays: 14
    scheduling:
      purge:
        cron: "0 0 1 * * *"
        enabled: false
    security:
      crypto:
        manualCTAuthoritySecretKey: f55d39487b91c00ad24d4fc70f54511539ed308e954ab859734598d16d047bdf

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:cleadb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group1
    template:
      default-topic: cleaQrCodes
