spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cleadb
    username: username
    password: password
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: kafka:29092