clea:
  conf:
    cleaClockDriftInSecs: 300
    driftBetweenDeviceAndOfficialTimeInSecs: 300
    retentionDurationInDays: 14
    scheduling:
      purge:
        cron: "0 0 1 * * *"
        enabled: false
    security:
      crypto:
        manualCTAuthoritySecretKey: f55d39487b91c00ad24d4fc70f54511539ed308e954ab859734598d16d047bdf
    exposure:
      enabled: "true"
      rules: # FIXME: change with real values
        # venueType, venueCat1, venueCat2, exposureTimeBackward, exposureTimeForward, exposureTimeStaffBackward, exposureTimeStaffForward
        - '1,1,1,3,13,23,33'
        - '*,*,*,2,12,22,32'
        - '3,*,*,1,11,21,31'
        - '1,2,3,2,12,22,32'
        - '*,2,*,2,12,22,32'
        - '*,*,3,2,12,22,32'
      risk:
        enabled: "false"
management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:cleadb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group1
    template:
      default-topic: cleaQrCodes
