server:
  port: 8055
application.name: "qrcode"

info:
  name: "qrcode"
  version: "01.00.04-SNAPSHOT"
  java.version: "1.8.0_172"

management:
  endpoints:
    web:
      base-path: "/private/manage"

spring:
  flyway:
    locations: "classpath:db/migration/postgresql"
    table: "SCHEMA_VERSION"
  datasource:
    hikari:
      max-lifetime: 290000
    url: jdbc:postgresql://postgrescaptcha:5432/qr
    username:  robert
    password: robert


captcha:
  validation:
    caseSensitive: false
  default:
    type: "IMAGE"
    locale: "fr"
  purge:
    lockAtMostFor: "5m"
    cron: "0 0/5 * * * ?"
    lifetimeInMs: 300000
  image:
    length: 4
    widthPerChar: 30
    characterSpacing: 5
  audio:
    length: 4