-- CREATE DATABASE CLEADB;
\c cleadb
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE ROLE username LOGIN PASSWORD 'password';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO username;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO username;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO username;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO username;
GRANT TRUNCATE ON ALL TABLES IN SCHEMA public TO username;
GRANT SELECT,USAGE ON ALL SEQUENCES IN SCHEMA public TO username;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE, DELETE, TRUNCATE ON TABLES TO username;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO username;

CREATE ROLE cleaadm LOGIN PASSWORD 'admin';
GRANT ALL PRIVILEGES ON SCHEMA public TO cleaadm;
