CREATE DATABASE CLEA;
CREATE ROLE cleaowner NOLOGIN;

CREATE ROLE clea LOGIN PASSWORD 'aelc';

-- ALTER DATABASE clea OWNER cleaowner;
GRANT ALL PRIVILEGES ON DATABASE clea TO clea WITH GRANT OPTION;

\c clea;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
