apiVersion: apps/v1
kind: Deployment
metadata:
  name: robert-ws-deployment
  namespace: robert-ws
  labels:
    app: robert-ws
spec:
  selector:
    matchLabels:
      app: robert-ws
  template:
    metadata:
      labels:
        app: robert-ws
    spec:
      containers:
        - name: robert-ws-app
          image: ws-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: ROBERTWS_EPHEMERALTUPLESBUNDLEDAYS
              value: "4"
            - name: ROBERTWS_MINEPOCHSBETWEENSTATUSREQUESTS
              value: "0"
            - name: ROBERTWS_MAXAUTHREQUESTCLOCKSKEW
              value: 10d
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: robert-ws-secrets
                  key: SPRING_DATA_MONGODB_URI
            - name: ROBERTWS_CRYPTOSERVERURI
              value: dns:///robert-crypto-service.robert-crypto:8080
            - name: ROBERTWS_PUSHSERVERBASEURL
              value: http://fake/private/api/v1
            - name: ROBERTWS_CAPTCHASERVER_BASEURL
              value: http://captcha-server-service.captcha.svc.cluster.local/private/api/v1
            - name: ROBERTWS_SUBMISSIONCODESERVERBASEURL
              value: http://submission-code-server-service.submission-code.svc.cluster.local/api/v1
            - name: ROBERTWS_REPORTVALIDATIONJWT_SIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: robert-ws-secrets
                  key: ROBERTWS_REPORTVALIDATIONJWT_SIGNINGKEY
            - name: ROBERTWS_DECLARATIONJWT_SIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: robert-ws-secrets
                  key: ROBERTWS_DECLARATIONJWT_SIGNINGKEY
            - name: ROBERTWS_DECLARATIONJWT_KID
              value: public-kid
            - name: ROBERTWS_ANALYTICSJWT_SIGNINGKEY
              valueFrom:
                secretKeyRef:
                  name: robert-ws-secrets
                  key: ROBERTWS_ANALYTICSJWT_SIGNINGKEY
            - name: MANAGEMENT_SERVER_PORT
              value: "8081"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,info,prometheus
      imagePullSecrets:
        - name: poc-inttac-poc-img-push-pull-secret
      nodeSelector:
        caascad.io/nodepool: "pod-tac"
