apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: e2e-robert-ws-logs
  namespace: robert-ws
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
