package fr.gouv.stopc.robert.server.batch.enums;

public final class StepNameEnum {

    public static final String POPULATE_REGISTRATION_ID_MAPPING_FOR_PURGE_STEP_NAME = "POPULATE_REGISTRATION_ID_MAPPING_FOR_PURGE_STEP";

    public static final String POPULATE_REGISTRATION_ID_MAPPING_FOR_RISK_RESET_STEP_NAME = "POPULATE_REGISTRATION_ID_MAPPING_FOR_RISK_RESET_STEP";

    public static final String PURGE_OLD_EXPOSITIONS_STEP_NAME = "PURGE_OLD_EXPOSITIONS_STEP";

    public static final String PURGE_OLD_EXPOSITIONS_PARTITIONER_STEP_NAME = "PURGE_OLD_EXPOSITIONS_PARTITIONER_STEP";

    public static final String PURGE_OLD_EXPOSITIONS_WORKER_STEP_NAME = "PURGE_OLD_EXPOSITIONS_WORKER_STEP";

    public static final String POPULATE_CONTACT_ID_MAPPING_STEP_NAME = "POPULATE_CONTACT_ID_MAPPING_STEP";

    public static final String POPULATE_REGISTRATION_WITH_SCORE_STEP_NAME = "POPULATE_REGISTRATION_WITH_SCORE_STEP";

    public static final String SCORING_CONTACT_STEP_NAME = "SCORING_CONTACT_STEP";

    public static final String SCORING_CONTACT_WORKER_STEP_NAME = "SCORING_CONTACT_WORKER_STEP";

    public static final String SCORING_CONTACT_PARTITIONER_STEP_NAME = "SCORING_CONTACT_PARTITIONER_STEP";

    public static final String REGISTRATION_RISK_EVALUATION_STEP_NAME = "REGISTRATION_RISK_EVALUATION_STEP";

    public static final String REGISTRATION_RISK_EVALUATION_PARTITIONER_STEP_NAME = "REGISTRATION_RISK_EVALUATION_PARTITIONER_STEP";

    public static final String REGISTRATION_RISK_EVALUATION_WORKER_STEP_NAME = "REGISTRATION_RISK_EVALUATION_WORKER_STEP";

    public static final String REGISTRATION_RISK_RESET_STEP_NAME = "REGISTRATION_RISK_RESET_STEP";

    public static final String REGISTRATION_RISK_RESET_PARTITIONER_STEP_NAME = "REGISTRATION_RISK_RESET_PARTITIONER_STEP";

    public static final String REGISTRATION_RISK_RESET_WORKER_STEP_NAME = "REGISTRATION_RISK_RESET_WORKER_STEP";

    private StepNameEnum() {
    }

}
