emulator:
  robert-ws-url: https://api-ppd.tousanticovid.gouv.fr/api/v6
  robert-crypto-public-key: "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwpDgJdE0aRop5uibRYqCOLK7CnZ+DAyQhGrVD6XYXC/5LeNtLwqSxPAVcswqtiZyPs68h2Y3KEQn2y2bRxRzQg=="
