package fr.gouv.stopc.e2e.mobileApplication.model;

import lombok.Value;

import java.util.Base64;

/**
 * A "ContactTuple" is a couple (ebid, ecc) for a given epochId.
 *
 * @see <a href=
 *      "https://github.com/ROBERT-proximity-tracing/documents/blob/master/ROBERT-specification-EN-v1_1.pdf">Robert
 *      Protocol 1.1</a> §5
 */
@Value
public class ContactTuple {

    /**
     * The encrypted country code (8 bits)
     */
    byte[] ebid;

    /**
     * Ephemeral Bluetooth ID at epoch i, generated by the back-end (64 bits)
     */
    byte[] ecc;

    @Override
    public String toString() {
        final var base64 = Base64.getEncoder();
        final var ebidB64 = base64.encodeToString(ebid);
        final var eccB64 = base64.encodeToString(ecc);
        return String.format("ContactTuple(ebid=%s, ecc=%s)", ebidB64, eccB64);
    }
}
