robert-ws:
  country-code: 33
  service-start-date: 2020-06-01
  captcha-server.enabled: yes
  max-auth-request-clock-skew: 1m
  min-epochs-between-status-requests: 2
  ephemeral-tuples-bundle-days: 4
  report-validation-jwt.validity-duration: 5m
  analytics-jwt.validity-duration: 6h

spring:
  codec.max-in-memory-size: 250MB
  cloud.vault.enabled: false

management:
  server.port: 8081
  endpoints.web.exposure.include: health,info,prometheus
