openapi: 3.0.0
info:
  description: "#STOPCOVID, Robert Proximity Tracing Client API"
  version: "2"
  title: "#STOPCOVID, Robert Proximity Tracing"
  termsOfService: https://github.com/ROBERT-proximity-tracing/
  contact:
    email: stopcovid@inria.fr
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about ROBERT
  url: https://github.com/ROBERT-proximity-tracing/
servers:
  - url: /internal/api/v2
paths:
  /kpis:
    get:
      tags: ["Kpi"]
      summary: Get KPIs
      description: >-
        Get current kpis produced

        NOTE: This API must be protected and used only by a trusted back-end server over a secure private connection.
      operationId: kpis
      responses:
        "200":
          description: Returns the current kpis
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RobertServerKpi"
        "400":
          description: bad request
components:
  schemas:
    RobertServerKpi:
      type: object
      properties:
        alertedUsers:
          type: integer
          format: int64
        exposedButNotAtRiskUsers:
          type: integer
          format: int64
        infectedUsersNotNotified:
          type: integer
          format: int64
        notifiedUsersScoredAgain:
          type: integer
          format: int64
        notifiedUsers:
          type: integer
          format: int64
        usersAboveRiskThresholdButRetentionPeriodExpired:
          type: integer
          format: int64
        reportsCount:
          type: integer
          format: int64
      required:
        - alertedUsers
        - exposedButNotAtRiskUsers
        - infectedUsersNotNotified
        - notifiedUsersScoredAgain
        - notifiedUsers
        - usersAboveRiskThresholdButRetentionPeriodExpired
        - reportsCount
