openapi: 3.0.0
info:
  version: 1.0.0
  title: Captcha API
  contact:
    email: stopcovid@inria.fr
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags: []
paths:
  /captcha:
    post:
      tags: ["captcha"]
      summary: Create a CAPTCHA
      description: |-
        Request the creation of a CAPTCHA challenge. A CAPTCHA Id is returned.


        Both CAPTCHA Id and CAPTCHA resolution must be provided as input to the /register service.


        A locale must be passed to localize the CAPTCHA.


        A type must be passed to request visual/audio format.
      operationId: captcha
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CaptchaCreateRequest"
      responses:
        "201":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CaptchaCreateResponse"
        "400":
          description: bad request
      security: []
  /captcha/{captchaId}/image:
    get:
      tags: ["captcha"]
      summary: Get image CAPTCHA
      description: Get image version of the CAPTCHA challenge
      operationId: captchaChallengeImage
      parameters:
        - name: captchaId
          in: path
          description: CAPTCHA Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            image/png:
              schema:
                type: string
                format: binary
        "400":
          description: CAPTCHA Id not found
        "404":
          description: CAPTCHA Id not found, bad URL pattern
        "410":
          description: CAPTCHA Id already used
      security: []
  /captcha/{captchaId}/audio:
    get:
      tags: ["captcha"]
      summary: Get audio CAPTCHA
      description: Get audio version of the CAPTCHA challenge
      operationId: captchaChallengeAudio
      parameters:
        - name: captchaId
          in: path
          description: CAPTCHA Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        "400":
          description: CAPTCHA Id not found
        "404":
          description: CAPTCHA Id not found, bad URL pattern
        "410":
          description: CAPTCHA Id already used
      security: []
components:
  schemas:
    CaptchaCreateRequest:
      type: object
      properties:
        type:
          type: string
          description: IMAGE or AUDIO (provided for accessibility)
        locale:
          type: string
          description: |-
            The locale that will be used to generate the CAPTCHA as an image or an audio clip.

            Supported locales for IMAGE: "ar" for arabic alphabet; defaults to latin characters

            Supported locales for AUDIO: "en", "es", "ar", "pt", "de", "it", "fr"; defaults to "fr"
      required:
        - type
        - locale
    CaptchaCreateResponse:
      type: object
      properties:
        id:
          type: string
          description: The ID of the generated CAPTCHA
      required:
        - id
