apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: robert-crypto-hpa
  labels:
    app: robert-crypto
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: robert-crypto-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
