#! /bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
SCRIPTNAME=`basename $0`
OPTIONS="-p $SCRIPTNAME -f $SCRIPTPATH/docker-compose.yml $OVERRIDES"

# IP of the host (bridge)
export EXTERNAL_IP=$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
  restart)
    shift
    docker-compose $OPTIONS stop $*
    docker-compose $OPTIONS rm -f $*
    docker-compose $OPTIONS up -d $*
    exit 
    ;;

  -o|--override)
    shift
    name=$1
    shift
    if [ -f $SCRIPTPATH/docker-compose_override_$name.yml ] ; then
       OPTIONS="${OPTIONS} -f $SCRIPTPATH/docker-compose_override_$name.yml"

      # specific to ssl, kafdrop need a base64 of the generated truststore
      if [ ! -f "$SCRIPTPATH/kafka/certs/truststore.jks" ] ; then 
         echo "Truststore not generated, use 'kafka/make_certs.sh kafka broker' "
         exit 1
      else
        export B64_TRUSTSTORE="$(cat $SCRIPTPATH/kafka/certs/truststore.jks | base64 -w 0)"
      fi
    else 
       echo "file docker-compose_override_$name.yml not found"
       exit 1
    fi
    ;;

  *)
    break
    ;;
esac
done

docker-compose $OPTIONS $*


