version: "3.8"
services:
  grafana:
    image: grafana/grafana:7.5.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    networks:
      - clea-network

networks:
  clea-network:
    driver: bridge
    name: clea-network

