version: "3.8"
services:
  # ADD NGinx and Kong

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - public
      - clea-network

  kong:
    image: kong:2.3
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr 
      KONG_ADMIN_ERROR_LOG: /dev/stderr 
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
    - ./kong/kong.yml:/home/kong/kong.yml:ro
    networks:
      - clea-network
  konga:
    image: pantsel/konga:next
    environment:
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      NODE_ENV: production
      KONGA_LOG_LEVEL: silly
    ports:
      - "1337:1337"
    networks:
      - clea-network

networks:
  public: 
    driver: bridge
    name: public
