robert:
  crypto.server:
    host: ${ROBERT_CRYPTO_SERVER_HOST:localhost}
    port: ${ROBERT_CRYPTO_SERVER_PORT:9090}
  server:
    time-start: ${ROBERT_SERVER_TIMESTART:2020-06-01}
    server.country-code: ${ROBERT_SERVER_COUNTRY_CODE:0x21}
  scoring:
    soft-max-a: ${ROBERT_SCORING_SOFT_MAX_A:4.342}
    algo-version: ${ROBERT_SCORING_ALGO_VERSION:2}
    batch-mode: ${ROBERT_SCORING_BATCH_MODE:SCORE_CONTACTS_AND_COMPUTE_RISK}
  protocol.hello-message-timestamp-tolerance: ${ROBERT_PROTOCOL_HELLO_TOLERANCE:180}

robert-batch.risk-threshold.last-contact-delay: P7D

spring.cloud:
  consul.enabled: false
  vault.enabled: false
