robert-crypto:
  service-start-date: 2020-06-01
  keystore-password: 1234
  keystore-configuration-uri: /config/SoftHSMv2/softhsm2.cfg
  hello-message-timestamp-tolerance: 3m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/robert
    username: robert
    password: robert
  cloud.vault.enabled: false

management:
  server.port: 8081
  endpoints.web.exposure.include: health,info,prometheus
