robert.crypto.server:
  port: ${ROBERT_CRYPTO_SERVER_PORT:9090}
  keystore:
    file: not-mandatory-in-production
    type: PKCS11
    password: ${ROBERT_CRYPTO_SERVER_KEYSTORE_PASSWORD:1234}
    config.file: ${ROBERT_CRYPTO_SERVER_CONFIG_FILE:/config/SoftHSMv2/softhsm2.cfg}

spring:
  datasource:
    url: ${ROBERT_CRYPTO_SERVER_DB_URL:jdbc:postgresql://localhost:5432/robert}
    username: ${ROBERT_CRYPTO_SERVER_DB_USR:robert}
    password: ${ROBERT_CRYPTO_SERVER_DB_PWD:robert}
  jpa:
    hibernate:
      ddl-auto: update

robert:
  server:
    time-start: ${ROBERT_SERVER_TIMESTART:20200601}
  protocol:
    hello-message-timestamp-tolerance: ${ROBERT_PROTOCOL_HELLO_TOLERANCE:180}
