robert-crypto:
  server-port: 8080
  service-start-date: 2020-06-01
  keystore-password: 1234
  keystore-configuration-uri: /config/SoftHSMv2/softhsm2.cfg
  hello-message-timestamp-tolerance: 3m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/robert
    username: robert
    password: robert
  cloud.vault.enabled: false

# we don't need webserver, that's why we expose it on the same port as management-port
server.port: ${management.server.port}

management:
  server.port: 8081
  endpoints.web.exposure.include: health,info,prometheus
